table DimAccount

	column account_id
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: account_id

	column account_name
		dataType: string
		summarizeBy: none
		sourceColumn: account_name

	column country
		dataType: string
		dataCategory: Country
		summarizeBy: none
		sourceColumn: country

	column region
		dataType: string
		summarizeBy: none
		sourceColumn: region

	column city
		dataType: string
		dataCategory: City
		summarizeBy: none
		sourceColumn: city

	column latitude
		dataType: double
		dataCategory: Latitude
		summarizeBy: none
		sourceColumn: latitude

	column longitude
		dataType: double
		dataCategory: Longitude
		summarizeBy: none
		sourceColumn: longitude

	column segment
		dataType: string
		summarizeBy: none
		sourceColumn: segment

	column industry
		dataType: string
		summarizeBy: none
		sourceColumn: industry

	partition DimAccount = m
		mode: import
		source =
			let
			    Source = Csv.Document(ReadProjectFile("raw/accounts.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Types = Table.TransformColumnTypes(Headers, {
			        {"account_id", type text}, {"account_name", type text}, {"country", type text},
			        {"region", type text}, {"city", type text}, {"latitude", type number},
			        {"longitude", type number}, {"segment", type text}, {"industry", type text}
			    }, "en-US"),
			    NormalizedCountry = Table.TransformColumns(Types, {{"country", NormalizeCountry}}),
			    Deduplicated = Table.Distinct(NormalizedCountry, {"account_id"})
			in
			    Deduplicated
