table DimDate

	column date
		dataType: dateTime
		isKey
		summarizeBy: none
		sourceColumn: date

	column year
		dataType: int64
		summarizeBy: none
		sourceColumn: year

	column month_number
		dataType: int64
		summarizeBy: none
		sourceColumn: month_number

	column month
		dataType: string
		sortByColumn: month_number
		summarizeBy: none
		sourceColumn: month

	column year_month
		dataType: string
		sortByColumn: month_start
		summarizeBy: none
		sourceColumn: year_month

	column month_start
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month_start

	column is_working_day
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_working_day

	partition DimDate = m
		mode: import
		source =
			let
			    Source = Csv.Document(ReadProjectFile("raw/monthly_metrics.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    DatesOnly = Table.TransformColumnTypes(Table.SelectColumns(Headers, {"month_date"}), {{"month_date", type date}}, "en-US"),
			    MinDate = List.Min(DatesOnly[month_date]),
			    MaxDate = List.Max(DatesOnly[month_date]),
			    Calendar = Table.FromList(List.Dates(MinDate, Duration.Days(MaxDate - MinDate) + 1, #duration(1, 0, 0, 0)), Splitter.SplitByNothing(), {"date"}),
			    Typed = Table.TransformColumnTypes(Calendar, {{"date", type date}}),
			    Year = Table.AddColumn(Typed, "year", each Date.Year([date]), Int64.Type),
			    MonthNumber = Table.AddColumn(Year, "month_number", each Date.Month([date]), Int64.Type),
			    Month = Table.AddColumn(MonthNumber, "month", each Date.ToText([date], "MMM", "en-US"), type text),
			    YearMonth = Table.AddColumn(Month, "year_month", each Date.ToText([date], "yyyy-MM", "en-US"), type text),
			    MonthStart = Table.AddColumn(YearMonth, "month_start", each Date.StartOfMonth([date]), type date),
			    IsWorkingDay = Table.AddColumn(MonthStart, "is_working_day", each Date.DayOfWeek([date], Day.Monday) < 5, type logical)
			in
			    IsWorkingDay
