table DimPlan

	column plan_name
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: plan_name

	column tier
		dataType: string
		summarizeBy: none
		sourceColumn: tier

	column monthly_price_eur
		dataType: double
		summarizeBy: none
		sourceColumn: monthly_price_eur

	column annual_price_eur
		dataType: double
		summarizeBy: none
		sourceColumn: annual_price_eur

	column max_users
		dataType: int64
		summarizeBy: none
		sourceColumn: max_users

	column churn_base
		dataType: double
		summarizeBy: none
		sourceColumn: churn_base

	partition DimPlan = m
		mode: import
		source =
			let
			    Source = Csv.Document(ReadProjectFile("reference/plans_catalog.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Types = Table.TransformColumnTypes(Headers, {
			        {"plan_name", type text}, {"tier", type text}, {"monthly_price_eur", type number},
			        {"annual_price_eur", type number}, {"max_users", Int64.Type}, {"churn_base", type number}
			    }, "en-US")
			in
			    Types
