table FactMonthlyMetrics

	column month_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: month_date

	column subscription_id
		dataType: string
		summarizeBy: none
		sourceColumn: subscription_id

	column account_id
		dataType: string
		summarizeBy: none
		sourceColumn: account_id

	column plan_name
		dataType: string
		summarizeBy: none
		sourceColumn: plan_name

	column mrr_eur
		dataType: double
		summarizeBy: none
		sourceColumn: mrr_eur

	column active_users
		dataType: int64
		summarizeBy: none
		sourceColumn: active_users

	column licensed_users
		dataType: int64
		summarizeBy: none
		sourceColumn: licensed_users

	column active_user_ratio
		dataType: double
		summarizeBy: none
		sourceColumn: active_user_ratio

	column api_calls
		dataType: int64
		summarizeBy: none
		sourceColumn: api_calls

	column storage_gb
		dataType: double
		summarizeBy: none
		sourceColumn: storage_gb

	column feature_adoption_pct
		dataType: double
		summarizeBy: none
		sourceColumn: feature_adoption_pct

	column nps_score
		dataType: int64
		summarizeBy: none
		sourceColumn: nps_score

	column revenue_at_risk_eur
		dataType: double
		summarizeBy: none
		sourceColumn: revenue_at_risk_eur

	partition FactMonthlyMetrics = m
		mode: import
		source =
			let
			    Source = Csv.Document(ReadProjectFile("raw/monthly_metrics.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Types = Table.TransformColumnTypes(Headers, {
			        {"month_date", type date}, {"subscription_id", type text}, {"account_id", type text},
			        {"plan_name", type text}, {"mrr_eur", type number}, {"active_users", Int64.Type},
			        {"licensed_users", Int64.Type}, {"active_user_ratio", type number}, {"api_calls", Int64.Type},
			        {"storage_gb", type number}, {"feature_adoption_pct", type number},
			        {"nps_score", Int64.Type}, {"revenue_at_risk_eur", type number}
			    }, "en-US")
			in
			    Types
